version: '3.8'

services:
  backend:
    container_name: be_app
    restart: always
    build:
      context: .
      target: production
    ports:
      - 3333:3333
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql:
    container_name: be_mysql_app
    image: mysql:latest
    environment:
      MYSQL_DATABASE: my-food-plan-it
      MYSQL_USER: tinkeruser
      MYSQL_PASSWORD: tinkerph
      MYSQL_ROOT_PASSWORD: tinkerph
    ports:
      - '3300:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
